# Site settings
title: Blog | Juan Carlos García 
header-img: img/home-bg.jpg
email: jugade92@gmail.com
description: "Juan Carlos García Blog"
baseurl: ""
url: "http://jcagarcia.github.io"
twitter_username: juancaFX
github_username:  jcagarcia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
